services:
  kong:
    image: kong:3.7
    container_name: libraryapp-kong
    environment:
      KONG_ROLE: "data_plane"
      KONG_DATABASE: "off"
      KONG_CLUSTER_MTLS: "pki"
      KONG_CLUSTER_CERT: "/etc/secrets/tls.crt"
      KONG_CLUSTER_CERT_KEY: "/etc/secrets/tls.key"
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: "system"
      KONG_KONNECT_MODE: "on"
      KONG_VITALS: "off"
      KONG_NGINX_WORKER_PROCESSES: "auto"
      KONG_UPSTREAM_KEEPALIVE_MAX_REQUESTS: 100000
      KONG_NGINX_HTTP_KEEPALIVE_REQUESTS: 100000
      KONG_PROXY_ACCESS_LOG: "off"
      KONG_DNS_STALE_TTL: 3600
      KONG_CLUSTER_CONTROL_PLANE: "bffefca93c.in.cp.konghq.com:443"
      KONG_CLUSTER_SERVER_NAME: "bffefca93c.in.cp.konghq.com"
      KONG_CLUSTER_TELEMETRY_ENDPOINT: "bffefca93c.in.tp.konghq.com:443"
      KONG_CLUSTER_TELEMETRY_SERVER_NAME: "bffefca93c.in.tp.konghq.com"
      KONG_ROUTER_FLAVOR: "expressions"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_LOG_LEVEL: "notice"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
    volumes:
      - ./gateway/kong.yml:/etc/kong/kong.yml:ro
      - ./gateway/tls.crt:/etc/secrets/tls.crt:ro
      - ./gateway/tls.key:/etc/secrets/tls.key:ro
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "8080:8000"
      - "8001:8001"
    restart: unless-stopped
