// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDEZITb12Z1_DzKfTPfqHyUrR_iTC8lQk',
    appId: '1:472325483862:web:7ded5e8262b4ad66457af7',
    messagingSenderId: '472325483862',
    projectId: 'libraryapp-c781e',
    authDomain: 'libraryapp-c781e.firebaseapp.com',
    storageBucket: 'libraryapp-c781e.firebasestorage.app',
    measurementId: 'G-475KD68482',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBennOgvjgtL7G9WKbWNmeuyNlzPeRLfRQ',
    appId: '1:472325483862:android:4e92d256d4cd5ee0457af7',
    messagingSenderId: '472325483862',
    projectId: 'libraryapp-c781e',
    storageBucket: 'libraryapp-c781e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG5z8iGrOi6LGRPD0aCRWWE8oedoDfGWE',
    appId: '1:472325483862:ios:9ea75d709a603273457af7',
    messagingSenderId: '472325483862',
    projectId: 'libraryapp-c781e',
    storageBucket: 'libraryapp-c781e.firebasestorage.app',
    iosBundleId: 'com.focus.libraryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG5z8iGrOi6LGRPD0aCRWWE8oedoDfGWE',
    appId: '1:472325483862:ios:9ea75d709a603273457af7',
    messagingSenderId: '472325483862',
    projectId: 'libraryapp-c781e',
    storageBucket: 'libraryapp-c781e.firebasestorage.app',
    iosBundleId: 'com.focus.libraryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDEZITb12Z1_DzKfTPfqHyUrR_iTC8lQk',
    appId: '1:472325483862:web:7ded5e8262b4ad66457af7',
    messagingSenderId: '472325483862',
    projectId: 'libraryapp-c781e',
    authDomain: 'libraryapp-c781e.firebaseapp.com',
    storageBucket: 'libraryapp-c781e.firebasestorage.app',
    measurementId: 'G-475KD68482',
  );
}
