// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASicO8R2ovjZggSoGdWMa6rs7ygIntQWY',
    appId: '1:1012554723765:web:9b7eecc4344f34ace7e9fc',
    messagingSenderId: '1012554723765',
    projectId: 'libraryapp-eecd8',
    authDomain: 'libraryapp-eecd8.firebaseapp.com',
    storageBucket: 'libraryapp-eecd8.firebasestorage.app',
    measurementId: 'G-8QS7B51Y09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMrkdbQTnIk2vciuRR7pThjTw1U212pAE',
    appId: '1:1012554723765:android:b7fab1bb7cbda67de7e9fc',
    messagingSenderId: '1012554723765',
    projectId: 'libraryapp-eecd8',
    storageBucket: 'libraryapp-eecd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvrsUQ_78R5YNoNsRpwkZV8EDNBCPI780',
    appId: '1:1012554723765:ios:64c9443277fca9c9e7e9fc',
    messagingSenderId: '1012554723765',
    projectId: 'libraryapp-eecd8',
    storageBucket: 'libraryapp-eecd8.firebasestorage.app',
    iosBundleId: 'com.example.libraryapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvrsUQ_78R5YNoNsRpwkZV8EDNBCPI780',
    appId: '1:1012554723765:ios:64c9443277fca9c9e7e9fc',
    messagingSenderId: '1012554723765',
    projectId: 'libraryapp-eecd8',
    storageBucket: 'libraryapp-eecd8.firebasestorage.app',
    iosBundleId: 'com.example.libraryapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASicO8R2ovjZggSoGdWMa6rs7ygIntQWY',
    appId: '1:1012554723765:web:3b02648e770b4b8fe7e9fc',
    messagingSenderId: '1012554723765',
    projectId: 'libraryapp-eecd8',
    authDomain: 'libraryapp-eecd8.firebaseapp.com',
    storageBucket: 'libraryapp-eecd8.firebasestorage.app',
    measurementId: 'G-C6GRBYGNEP',
  );
}
